### ISSUE TITLE
encode_package fails: Errno 24

### ISSUE THREAD

**Issue by Funkton** [ChrisHughes/chitu-image-tool#2]
On attempt to encode package the function fails with error code 24, Too many open files:

![Screen Shot 2020-09-15 at 1 51 50 AM](https://user-images.githubusercontent.com/5308216/93188620-0e44d080-f6f6-11ea-8d89-84b963fef767.png)

**Comment by ChrisHughes** [comment]
I've pushed a fix for this issue, can you try again

**Comment by Funkton** [comment]
Hey, thanks for pushing that out so quick. The process went along a lot farther, but still ended with an error.
![Screen Shot 2020-09-15 at 2 21 54 AM](https://user-images.githubusercontent.com/5308216/93192352-70073980-f6fa-11ea-8a2b-98a1db3deff8.png)

**Comment by ChrisHughes** [comment]
There was a misplaced assertion in code, I've pushed a fix for this, can you pull and try again.

**Comment by Funkton** [comment]
Now there is a type error. This showed up after running some of them through png optimizer.
<img width="447" alt="Screen Shot 2020-09-15 at 9 23 38 AM" src="https://user-images.githubusercontent.com/5308216/93238255-0c9afd00-f736-11ea-83af-c1c5093186d3.png">

Running it on a fresh decode yields an assertion error.
<img width="478" alt="Screen Shot 2020-09-15 at 9 29 42 AM" src="https://user-images.githubusercontent.com/5308216/93238312-20466380-f736-11ea-8329-e27d92a7316c.png">

**Comment by ChrisHughes** [comment]
Pushing a full UI package is a stretch goal of the tool and is fairly untested at this point, can you please send me the full zip file of the images you're trying to encode to 89dragon _at_ gmail.com and I'll see if I can spot any issues.
